gui:
  nerdFontsVersion: "3"

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

  branchLogCmd: "git log --graph --oneline --decorate --decorate-refs-exclude=refs/tags --color {{branchName}}"

os:
  editPreset: 'nvim'

keybinding:
  universal:
    nextTab: 'ø'
    prevTab: 'æ'

