[manager]

prepend_keymap = [
	{ on = "<Enter>", run = 'plugin --sync smart-enter', desc = "Enter child dir, or open the file" },
	{ on = "<Backspace>", run = 'leave', desc = "Leave child dir" },
  { on = "<C-s>", run = 'shell "$SHELL" --block --confirm' , desc = "Open shell" },
]

