[manager]

prepend_keymap = [
  { on = "<Enter>", run = 'plugin smart-enter', desc = "Enter child dir, or open the file" },
  { on = "<Backspace>", run = 'leave', desc = "Leave child dir" },
  { on = "<C-s>", run = 'shell "$SHELL" --block --confirm', desc = "Open shell" },

  { on = "i", run = "plugin searchjump", desc = "searchjump mode" },
  { on = "i", run = "plugin searchjump --args='autocd'", desc = "searchjump mode(auto cd select folder)" },
]
