[manager]
ratio = [1, 4, 3]
sort_by = "natural"
sort_dir_first = true
show_hidden = false

[opener]
edit = [
  { run = 'nvim "$@"', block = true, desc = "neovim", for = "linux" },
]

lnav = [
  { run = 'lnav "$@"', block = true, desc = "lnav", for = "linux" },
]

pdf = [
  { run = 'zathura "$@"', orphan = true, desc = "zathura", for = "linux" },
]

unzip = [
  { run = 'unzip "$@" -d "$(basename -s .zip "$@")" && rm -f "$@"', block = true, desc = "unzip", for = "linux" },
]

image = [
  { run = 'imv "$@"', orphan = true, desc = "imv", for = "linux" },
]

video = [
  { run = 'xdg-open "$@"', orphan = true, desc = "xdg-open", for = "linux" },
]

audio = [
  { run = 'xdg-open "$@"', orphan = true, desc = "xdg-open", for = "linux" },
]

fallback = [
  { run = 'xdg-open "$@"', orphan = true, desc = "xdg-open", for = "linux" },
]

[open]
rules = [
  { name = "*.log", use = ["lnav", "edit"] },
  { name = "*.txt", use = ["lnav", "edit"] },

  { mime = "text/*", use = "edit" },
  { mime = "application/pdf", use = "pdf" },

  { mime = "application/zip", use = "unzip" },
  { mime = "application/gzip", use = "archive" },
  { mime = "application/x-bzip", use = "archive" },
  { mime = "application/x-bzip2", use = "archive" },
  { mime = "application/x-tar", use = "archive" },
  { mime = "application/x-7z-compressed", use = "archive" },
  { mime = "application/x-rar", use = "archive" },

  { mime = "image/*", use = "image" },
  { mime = "audio/*", use = "audio" },

  # { mime = "video/*", use = "video" },
  # { mime = "application/json", use = "text" },
]

